import fs from 'node:fs';
import { createRequire } from 'node:module';
import ts from 'typescript';
const require = createRequire(import.meta.url);
const React = require('react');
const {renderToStaticMarkup} = require('react-dom/server');
const source = fs.readFileSync(new URL('../app/page.tsx',import.meta.url),'utf8');
const compiled = ts.transpileModule(source,{compilerOptions:{jsx:ts.JsxEmit.ReactJSX,module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;
const module={exports:{}};
new Function('require','module','exports',compiled)(require,module,module.exports);
const markup=renderToStaticMarkup(React.createElement(module.exports.default)).replace('<main>','<main id="top">');
const core=source.slice(source.indexOf('const WORDS'),source.indexOf('export default function')).replaceAll('export function','function');
const effect=source.slice(source.indexOf('    const canvas=canvasRef.current!;'),source.indexOf('    return()=>{cancelAnimationFrame'));
const browserCode=ts.transpileModule(core+`\nconst canvasRef={current:document.querySelector('canvas')};\nconst readoutRef={current:document.querySelector('.instrument > span')};\nconst tickRef={current:document.querySelector('.ruler i')};\n`+effect,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.None}}).outputText;
new Function(browserCode);
const css=fs.readFileSync(new URL('../app/globals.css',import.meta.url),'utf8').replace("@import 'tailwindcss';",'');
const html=`<!doctype html>\n<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="The machine generates the pattern. The human supplies the mind. An interactive editorial sketch."><title>A Beautiful Illusion</title><style>${css}</style></head><body>${markup}<script>${browserCode}</script></body></html>\n`;
fs.writeFileSync(new URL('../index.html',import.meta.url),html);
console.log('Standalone index.html exported with editorial content and interactive canvas.');
