"""Rebuild the saved day into 48 half-hour frames. Requires pyproj for map coordinates."""
import gzip
import hashlib
import json
import re
from pathlib import Path

from pyproj import Transformer

ROOT = Path(__file__).resolve().parent
SOURCE = ROOT / 'data/day-source.json.gz'
START, END = '2025-09-15T00:00:00', '2025-09-16T00:00:00'
QUERY = f'atvykimo_laikas>="{START}"&atvykimo_laikas<"{END}"&limit(50001)'
ENDPOINT = 'https://get.data.gov.lt/datasets/gov/sp/keleiviu_srautai/Stotele/:format/json'


def prepare():
    raw = gzip.decompress(SOURCE.read_bytes())
    rows = json.loads(raw)['_data']
    stops, seen = {}, set()
    frames = [dict(observations=0, boardings=0, alightings=0, stops={}) for _ in range(48)]
    project = Transformer.from_crs('EPSG:3346', 'EPSG:4326', always_xy=True)
    for row in rows:
        record = row['keliones_stoteles_id']
        if record in seen:
            raise ValueError(f'Duplicate record: {record}')
        seen.add(record)
        stamp = row['atvykimo_laikas']
        assert START <= stamp < END
        match = re.fullmatch(r'POINT \(([-\d.]+) ([-\d.]+)\)', row['geometrija_wkt'])
        if not match:
            raise ValueError(f'Unrecognized coordinates: {record}')
        north, east = map(float, match.groups())
        assert 6000000 < north < 6200000 and 400000 < east < 700000
        board, alight = row['ilipusiu_sk'], row['islipusiu_sk']
        assert isinstance(board, int) and board >= 0
        assert isinstance(alight, int) and alight >= 0
        key = (row['stoteles_id'], north, east)
        if key not in stops:
            # Source WKT uses north/east order; always_xy expects east/north.
            lon, lat = project.transform(east, north)
            assert 54 < lat < 56 and 24 < lon < 26
            stops[key] = dict(index=len(stops), id=row['stoteles_id'], name=row['pavadinimas'],
                              east=east, north=north, lat=round(lat, 7), lon=round(lon, 7))
        index = stops[key]['index']
        minute = int(stamp[11:13]) * 60 + int(stamp[14:16])
        frame = frames[minute // 30]
        # Sparse frames: absent key means no observation, never measured zero.
        stop = frame['stops'].setdefault(index, dict(boardings=0, alightings=0,
                                                    observations=0, first=stamp, last=stamp))
        for target in (frame, stop):
            target['boardings'] += board
            target['alightings'] += alight
            target['observations'] += 1
        stop['first'] = min(stop['first'], stamp)
        stop['last'] = max(stop['last'], stamp)
    assert rows and len(rows) < 50001, 'Sample may have reached the request cap'
    data = dict(source=ENDPOINT, query=QUERY, retrieved='2026-09-28',
                sourceSha256=hashlib.sha256(raw).hexdigest(), start=START, end=END,
                windowMinutes=30, records=len(rows), trips=len({r['reiso_id'] for r in rows}),
                boardings=sum(r['ilipusiu_sk'] for r in rows),
                alightings=sum(r['islipusiu_sk'] for r in rows),
                stops=list(stops.values()), frames=frames)
    assert sum(f['observations'] for f in frames) == data['records']
    for metric in ('boardings', 'alightings'):
        assert sum(f[metric] for f in frames) == data[metric]
        assert all(sum(s[metric] for s in f['stops'].values()) == f[metric] for f in frames)
    (ROOT / 'data/sample.js').write_text(
        '// Generated by prepare.py from day-source.json.gz; do not edit.\nwindow.VILNIUS_SAMPLE = '
        + json.dumps(data, ensure_ascii=False, separators=(',', ':')) + ';\n', encoding='utf-8')
    print(f"{len(rows)} observations → {len(stops)} stop positions / {len(frames)} half-hour frames; "
          f"{data['boardings']} boardings / {data['alightings']} alightings")


if __name__ == '__main__':
    prepare()
